#!/bin/sh
grep -h TUI_MOD $@ > tuidb_list.tmp
echo '/* This file was autogenerated with make_tuidb.sh */'
echo '#undef TUI_MOD'
echo '#define TUI_MOD(fn,ps,mn,wh,lc) static const unsigned char fn##_str[] PROGMEM = mn;'
cat tuidb_list.tmp
echo '#undef TUI_MOD'
echo '#define TUI_MOD(fn,ps,mn,wh,lc) void fn(uint8_t x, uint8_t y, uint8_t par);'
cat tuidb_list.tmp
echo '#undef TUI_MOD'
echo '#define TUI_MOD(fn,ps,mn,wh,lc) int ps(uint8_t prv);'
cat tuidb_list.tmp
echo '#undef TUI_MOD'
echo '#define TUI_MOD(fn,ps,mn,wh,lc) {(PGM_P)fn##_str, fn, ps, wh, lc},'
echo 'const struct tui_mod tuidb[] PROGMEM = {'
cat tuidb_list.tmp
echo '};'
echo '#undef TUI_MOD'
rm tuidb_list.tmp
